version: '3.8'

services:
  frontend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

  backend:
    environment:
      - FLASK_ENV=development
      - DEBUG=true
    volumes:
      - ./backend:/app
    command: python run.py

  redis:
    ports:
      - "6379:6379"

  worker:
    environment:
      - FLASK_ENV=development
      - DEBUG=true
    volumes:
      - ./backend:/app
      - ./engine:/app/engine
      - ./queue:/app/queue
      - ./storage:/app/storage
