name: StegnoX Tests

on:
  push:
    branches: [ main, develop, fix/github-workflow-updates ]
  pull_request:
    branches: [ main, develop ]

env:
  FLASK_ENV: testing
  JWT_SECRET_KEY: github_actions_test_key
  DATABASE_URL: sqlite:///test.db
  PYTHONPATH: ${{ github.workspace }}
  PYTHONUNBUFFERED: 1
  PYTHONWARNINGS: ignore::DeprecationWarning
  PYTHONDONTWRITEBYTECODE: 1
  PIP_USE_PEP517: "1"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9, '3.10']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Create test directories
      run: |
        mkdir -p tests/data
        mkdir -p storage/temp
        mkdir -p backend/instance
        chmod -R 777 tests/data storage/temp backend/instance || true
    
    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-opencv libopencv-dev
        sudo apt-get install -y libsm6 libxext6 libxrender-dev
        sudo apt-get install -y libgl1-mesa-glx
        sudo apt-get install -y sqlite3
    
    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install opencv sqlite
    
    - name: Install system dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install sqlite
      continue-on-error: true

    - name: Setup Python environment
      run: |
        python -m pip install --upgrade pip
      env:
        PYTHONPATH: ""
        PIP_NO_CACHE_DIR: "1"
        PIP_NO_WARN_SCRIPT_LOCATION: "1"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade setuptools wheel build
      env:
        PYTHONPATH: ""
        PIP_NO_CACHE_DIR: "1"
        PIP_NO_WARN_SCRIPT_LOCATION: "1"

    - name: Install base dependencies
      run: |
        python -m pip install --upgrade urllib3==2.0.7 requests==2.31.0 certifi==2024.2.2
        python -m pip install --upgrade charset-normalizer==3.3.2 idna==3.6
      env:
        PYTHONPATH: ""
        PIP_NO_BUILD_ISOLATION: "0"
        PIP_NO_DEPENDENCIES: "0"
        PIP_NO_CACHE_DIR: "1"

    - name: Install test dependencies
      run: |
        python -m pip install pytest==7.4.3 pytest-cov==4.1.0 pytest-env==1.1.1
        python -m pip install pytest-timeout==2.2.0 pytest-flask==1.3.0
      env:
        PYTHONPATH: ""
        PIP_NO_CACHE_DIR: "1"

    - name: Install project dependencies
      run: |
        python -m pip install -r requirements.txt --no-deps
        python -m pip install -e .
      env:
        PYTHONPATH: ${{ github.workspace }}
        PIP_NO_CACHE_DIR: "1"
        SETUPTOOLS_USE_DISTUTILS: "stdlib"

    - name: Verify imports
      run: |
        python -c "import urllib3; print('urllib3 version:', urllib3.__version__)"
        python -c "import requests; print('requests version:', requests.__version__)"
        python -c "import pytest; print('pytest version:', pytest.__version__)"
        python -c "import flask; print('flask version:', flask.__version__)"
      env:
        PYTHONPATH: ${{ github.workspace }}
    
    - name: Initialize test database
      run: |
        python -c "import sqlite3; conn = sqlite3.connect('test.db'); conn.close()"
        python -c "import sqlite3; conn = sqlite3.connect('backend/instance/test.db'); conn.close()"
    
    - name: Run unit tests
      run: |
        python -m pytest tests/ -v --tb=short
      env:
        PYTHONPATH: ${{ github.workspace }}
        FLASK_ENV: testing
        JWT_SECRET_KEY: github_actions_test_key
        DATABASE_URL: sqlite:///test.db
        SETUPTOOLS_USE_DISTUTILS: "stdlib"
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-opencv libopencv-dev
        sudo apt-get install -y libsm6 libxext6 libxrender-dev
        sudo apt-get install -y libgl1-mesa-glx
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements.txt
      env:
        PIP_USE_PEP517: "1"
        SETUPTOOLS_USE_DISTUTILS: "stdlib"
    
    - name: Run integration tests
      run: |
        python -m pytest tests/integration/ -v --tb=short
      env:
        PYTHONPATH: ${{ github.workspace }}
        FLASK_ENV: testing
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  e2e-test:
    runs-on: ubuntu-latest
    needs: integration-test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-opencv libopencv-dev
        sudo apt-get install -y libsm6 libxext6 libxrender-dev
        sudo apt-get install -y libgl1-mesa-glx
        sudo apt-get install -y google-chrome-stable
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements.txt
      env:
        PIP_USE_PEP517: "1"
        SETUPTOOLS_USE_DISTUTILS: "stdlib"
    
    - name: Run end-to-end tests
      run: |
        python -m pytest tests/e2e/ -v --tb=short
      env:
        PYTHONPATH: ${{ github.workspace }}
        FLASK_ENV: testing
